// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLny86itl1O0yE1j_nmVv2_Y9ub7QES28',
    appId: '1:585255872109:web:5c762cbd63f541eac5c164',
    messagingSenderId: '585255872109',
    projectId: 'mydexef',
    authDomain: 'mydexef.firebaseapp.com',
    storageBucket: 'mydexef.firebasestorage.app',
    measurementId: 'G-N7SY4L72H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYba9-ZswhGFwujFaFo8H0TFC2xwa6Gc',
    appId: '1:585255872109:android:05f3cfd00dd0c49ec5c164',
    messagingSenderId: '585255872109',
    projectId: 'mydexef',
    storageBucket: 'mydexef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACo75_GD8IVNOHwG9C0lQ2ArNrfaGXJtM',
    appId: '1:585255872109:ios:79fa279feb9cc593c5c164',
    messagingSenderId: '585255872109',
    projectId: 'mydexef',
    storageBucket: 'mydexef.firebasestorage.app',
    androidClientId: '585255872109-rltq7iah1ro4g7p3tkng8pjmc4u6inhb.apps.googleusercontent.com',
    iosClientId: '585255872109-qmbmre8kqmfkbih9r2cm4k8kaq1bot5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.authDexef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACo75_GD8IVNOHwG9C0lQ2ArNrfaGXJtM',
    appId: '1:585255872109:ios:79fa279feb9cc593c5c164',
    messagingSenderId: '585255872109',
    projectId: 'mydexef',
    storageBucket: 'mydexef.firebasestorage.app',
    androidClientId: '585255872109-rltq7iah1ro4g7p3tkng8pjmc4u6inhb.apps.googleusercontent.com',
    iosClientId: '585255872109-qmbmre8kqmfkbih9r2cm4k8kaq1bot5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.authDexef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBvZzBfw0ALv49mOHTlh0uD2rrVHDElJk',
    appId: '1:585255872109:web:2d29f27e104751e4c5c164',
    messagingSenderId: '585255872109',
    projectId: 'mydexef',
    authDomain: 'mydexef.firebaseapp.com',
    storageBucket: 'mydexef.firebasestorage.app',
    measurementId: 'G-FGYLHV971K',
  );
}
